import collections
kingDict = {
    '태조':'kaa',
    '정종':'kba',
    '태종':'kca',
    '세종':'kda',
    '문종':'kea',
    '단종':'kfa',
    '세조':'kga',
    '예종':'kha',
    '성종':'kia',
    '연산군':'kja',
    '중종':'kka',
    '인종':'kla',
    '명종':'kma',
    '선조':'kna',
    '선조(수정)':'knb',
    '광해군':'koa',
    '광해군(정초)':'kob',
    '인조':'kpa',
    '효종':'kqa',
    '현종':'kra',
    '현종(개수)':'krb',
    '숙종':'ksa',
    '숙종보궐':'ksb',
    '경종':'kta',
    '경종(수정)':'ktb',
    '영조':'kua',
    '정조':'kva',
    '순조':'kwa',
    '헌종':'kxa',
    '철종':'kya',
    '고종':'kza',
    '순종':'kzb',
    '순종부록':'kzc'
}
kings=['kaa', 'kba', 'kca', 'kda', 'kea', 'kfa', 'kga', 'kha', 'kia', 'kja', 'kka', 'kla', 'kma', 'kna', 'knb', 'koa', 'kob', 'kpa', 'kqa', 'kra', 'krb', 'ksa', 'ksb', 'kta', 'ktb', 'kua', 'kva', 'kwa', 'kxa', 'kya', 'kza', 'kzb', 'kzc']
